----------> uses
# use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#     use PlatformPolicy PlatformPolicy-* External (no_version_directory)
#       use GaudiPolicy *  (no_version_directory)
#         use LCG_Settings *  (no_version_directory)
#         use Python * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.9.p1)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#         use tcmalloc * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.4)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#           use libunwind v* LCG_Interfaces (no_version_directory) (native_version=5c2cade)
#             use LCG_Configuration v*  (no_version_directory)
#             use LCG_Settings v*  (no_version_directory)
#         use Reflex v* LCG_Interfaces (no_auto_imports) (no_version_directory)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#           use ROOT v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=6.04.16)
#             use LCG_Configuration v*  (no_version_directory)
#             use LCG_Settings v*  (no_version_directory)
#             use GCCXML v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=0.9.0_20131026)
#               use LCG_Configuration v*  (no_version_directory)
#               use LCG_Settings v*  (no_version_directory)
#             use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.9.p1)
#             use xrootd v* LCG_Interfaces (no_version_directory) (native_version=4.2.3)
#               use LCG_Configuration v*  (no_version_directory)
#               use LCG_Settings v*  (no_version_directory)
#       use AtlasCommonPolicy AtlasCommonPolicy-*  (no_version_directory)
#         use LCG_Platforms *  (no_version_directory)
#         use AtlasDoxygen AtlasDoxygen-* Tools (no_version_directory) (native_version=)
#           use LCG_Settings *  (no_version_directory)
#           use LCG_Configuration *  (no_version_directory)
#             use LCG_Platforms *  (no_version_directory)
#     use Mac105_Compat Mac105_Compat-* External (no_version_directory) (native_version=1.0.0)
#       use AtlasExternalArea AtlasExternalArea-* External (no_version_directory)
#         use LCG_Settings v*  (no_version_directory)
#         use PlatformPolicy PlatformPolicy-* External (no_version_directory)
#       use PlatformPolicy PlatformPolicy-* External (no_version_directory)
#   use AtlasCxxPolicy AtlasCxxPolicy-*  (no_version_directory)
#     use GaudiPolicy v*  (no_auto_imports) (no_version_directory)
#     use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#     use AtlasCompilers AtlasCompilers-* External (no_version_directory)
#       use LCG_Platforms *  (no_version_directory)
#     use CheckerGccPlugins CheckerGccPlugins-* External (no_version_directory) (native_version=CheckerGccPlugins-00-01-84)
#       use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#       use AtlasCompilers AtlasCompilers-* External (no_version_directory)
#   use AtlasCommonPolicy AtlasCommonPolicy-*  (no_version_directory)
#   use GaudiPolicy v*  (no_auto_imports) (no_version_directory)
#   use CodeCheck CodeCheck-* Tools (no_version_directory)
#   use AtlasDoxygen AtlasDoxygen-* Tools (no_version_directory) (native_version=)
# use AthAnalysisBaseRunTime AthAnalysisBaseRunTime-*  (no_version_directory)
#   use AtlasBoost AtlasBoost-* External (no_auto_imports) (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.59.0_python2.7)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#       use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.9.p1)
#   use AtlasEigen AtlasEigen-* External (no_auto_imports) (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use PyCmt PyCmt-* Tools (no_auto_imports) (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use AtlasPython AtlasPython-* External (no_auto_imports) (no_version_directory)
#         use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#         use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.9.p1)
#   use AtlasFastJet AtlasFastJet-* External (no_auto_imports) (no_version_directory) (native_version=3.2.0)
#     use AtlasExternalArea AtlasExternalArea-00-* External (no_version_directory)
#     use AtlasFortranPolicy AtlasFortranPolicy-*  (no_version_directory) (native_version=gcc-v-4.2.0-20060924)
#       use AtlasExternalArea AtlasExternalArea-* External (no_version_directory)
#       use AtlasCompilers AtlasCompilers-* External (no_version_directory)
#       use GaudiPolicy v*  (no_auto_imports) (no_version_directory)
#     use fastjet * LCG_Interfaces (no_version_directory) (native_version=3.2.0)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#   use AtlasFastJetContrib AtlasFastJetContrib-* External (no_auto_imports) (no_version_directory) (native_version=1.025)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#     use AtlasFastJet AtlasFastJet-* External (no_version_directory) (native_version=3.2.0)
#   use AtlasAIDA AtlasAIDA-* External (no_auto_imports) (no_version_directory)
#     use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#     use AIDA v* LCG_Interfaces (no_version_directory) (native_version=3.2.1)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#   use AtlasCLHEP AtlasCLHEP-* External (no_auto_imports) (no_version_directory) (native_version=2.1.2.3)
#     use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#     use CLHEP v* LCG_Interfaces (no_version_directory) (native_version=2.1.2.3)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#   use AtlasHepMC AtlasHepMC-* External (no_auto_imports) (no_version_directory) (native_version=2.06.09)
#     use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#     use LCG_Configuration v*  (no_version_directory)
#   use AtlasExternalArea AtlasExternalArea-* External (no_auto_imports) (no_version_directory)
#   use AtlasPyROOT AtlasPyROOT-* External (no_auto_imports) (no_version_directory)
#     use AtlasROOT AtlasROOT-02-* External (no_auto_imports) (no_version_directory)
#       use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#       use ROOT v* LCG_Interfaces (no_version_directory) (native_version=6.04.16)
#     use AtlasPython AtlasPython-00-* External (no_auto_imports) (no_version_directory)
#   use AtlasPython AtlasPython-* External (no_auto_imports) (no_version_directory)
#   use AtlasRELAX AtlasRELAX-* External (no_auto_imports) (no_version_directory)
#     use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#     use RELAX v* LCG_Interfaces (no_version_directory) (native_version=RELAX-root6)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#   use AtlasROOT AtlasROOT-* External (no_auto_imports) (no_version_directory)
#   use AtlasReflex AtlasReflex-* External (no_auto_imports) (no_version_directory)
#     use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#     use AtlasRELAX AtlasRELAX-* External (no_auto_imports) (no_version_directory)
#     use AtlasROOT AtlasROOT-* External (no_version_directory)
#   use AtlasValgrind AtlasValgrind-* External (no_auto_imports) (no_version_directory) (native_version=3.11.0)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use LCG_Settings v*  (no_version_directory)
#     use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#     use valgrind v* LCG_Interfaces (no_version_directory) (native_version=3.11.0)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#   use Lhapdf Lhapdf-* External (no_auto_imports) (no_version_directory) (native_version=6.1.5_lcgcmt67ca)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use AtlasExternalArea AtlasExternalArea-* External (no_version_directory)
#     use LCG_Configuration *  (no_version_directory)
#   use ExternalPolicy ExternalPolicy-* External (no_auto_imports) (no_version_directory)
#   use SLC4_Compat SLC4_Compat-* External (no_auto_imports) (no_version_directory) (native_version=1.0.3)
#     use AtlasExternalArea AtlasExternalArea-* External (no_version_directory)
#     use PlatformPolicy PlatformPolicy-* External (no_version_directory)
#   use SLC5_Compat SLC5_Compat-* External (no_auto_imports) (no_version_directory) (native_version=1.0.2)
#     use AtlasExternalArea AtlasExternalArea-* External (no_version_directory)
#     use PlatformPolicy PlatformPolicy-* External (no_version_directory)
#   use AtlasCOOL AtlasCOOL-* External (no_auto_imports) (no_version_directory)
#     use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#     use COOL v* LCG_Interfaces (no_version_directory) (native_version=3_1_0)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#       use CORAL v* LCG_Interfaces (no_version_directory) (native_version=3_1_0)
#         use LCG_Configuration v*  (no_version_directory)
#         use LCG_Settings v*  (no_version_directory)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.59.0_python2.7)
#       use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.9.p1)
#       use ROOT v* LCG_Interfaces (no_version_directory) (native_version=6.04.16)
#     use AtlasReflex AtlasReflex-00-* External (no_auto_imports) (no_version_directory)
#   use PathResolver PathResolver-* Tools (no_auto_imports) (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#     use GaudiInterface GaudiInterface-* External (no_version_directory)
#       use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#       use GaudiKernel v*  (no_version_directory)
#         use GaudiPolicy *  (no_version_directory)
#         use GaudiPluginService *  (no_version_directory)
#           use GaudiPolicy *  (no_version_directory)
#         use Reflex * LCG_Interfaces (no_version_directory)
#         use Boost * LCG_Interfaces (no_version_directory) (native_version=1.59.0_python2.7)
#     use AsgTools AsgTools-* Control/AthToolSupport (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use xAODRootAccess xAODRootAccess-* Control (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use AtlasROOT AtlasROOT-* External (no_version_directory)
#         use AthContainers AthContainers-* Control (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AthenaKernel AthenaKernel-* Control (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use uuid v* LCG_Interfaces (no_version_directory) (native_version=dummy)
#               use LCG_Configuration v*  (no_version_directory)
#               use LCG_Settings v*  (no_version_directory)
#             use GaudiInterface GaudiInterface-* External (no_version_directory)
#             use DataModelRoot DataModelRoot-* Control (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use AtlasROOT AtlasROOT-* External (no_version_directory)
#               use AtlasReflex AtlasReflex-* External (no_version_directory)
#             use CxxUtils CxxUtils-* Control (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#               use AtlasBoost AtlasBoost-* External (no_version_directory)
#             use AtlasBoost AtlasBoost-* External (no_version_directory)
#             use Scripts Scripts-* Tools (no_auto_imports) (no_version_directory)
#               use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use SGTools SGTools-* Control (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use CxxUtils CxxUtils-* Control (no_version_directory)
#             use AthenaKernel AthenaKernel-* Control (no_version_directory)
#             use AtlasBoost AtlasBoost-* External (no_version_directory)
#             use GaudiInterface GaudiInterface-* External (no_version_directory)
#           use CxxUtils CxxUtils-* Control (no_version_directory)
#           use AthContainersInterfaces AthContainersInterfaces-* Control (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use SGTools SGTools-* Control (no_version_directory)
#             use CxxUtils CxxUtils-* Control (no_version_directory)
#             use AtlasBoost AtlasBoost-* External (no_version_directory)
#           use AthLinks AthLinks-* Control (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use AthenaKernel AthenaKernel-* Control (no_version_directory)
#             use SGTools SGTools-* Control (no_version_directory)
#             use CxxUtils CxxUtils-* Control (no_version_directory)
#             use AtlasBoost AtlasBoost-* External (no_version_directory)
#             use GaudiInterface GaudiInterface-* External (no_version_directory)
#             use AtlasReflex AtlasReflex-* External (no_version_directory)
#           use AtlasBoost AtlasBoost-* External (no_version_directory)
#           use GaudiInterface GaudiInterface-* External (no_version_directory)
#         use AthContainersInterfaces AthContainersInterfaces-* Control (no_version_directory)
#         use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AthenaKernel AthenaKernel-* Control (no_version_directory)
#           use SGTools SGTools-* Control (no_version_directory)
#           use AthLinks AthLinks-* Control (no_version_directory)
#           use AthContainersInterfaces AthContainersInterfaces-* Control (no_version_directory)
#           use AthContainers AthContainers-* Control (no_version_directory)
#           use AtlasROOT AtlasROOT-* External (no_version_directory)
#           use CxxUtils CxxUtils-* Control (no_version_directory)
#         use xAODEventFormat xAODEventFormat-* Event/xAOD (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use xAODCore xAODCore-* Event/xAOD (no_version_directory)
#         use xAODRootAccessInterfaces xAODRootAccessInterfaces-* Control (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AtlasROOT AtlasROOT-* External (no_version_directory)
#       use GaudiInterface GaudiInterface-* External (no_version_directory)
#       use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use GaudiInterface GaudiInterface-* External (no_version_directory)
#         use AtlasROOT AtlasROOT-* External (no_version_directory)
#         use AthenaKernel AthenaKernel-* Control (no_version_directory)
#         use StoreGate StoreGate-* Control (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AthenaKernel AthenaKernel-* Control (no_version_directory)
#           use SGTools SGTools-* Control (no_version_directory)
#           use AtlasBoost AtlasBoost-* External (no_version_directory)
#           use AtlasTBB AtlasTBB-* External (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#             use PyCmt PyCmt-* Tools (no_auto_imports) (no_version_directory)
#           use GaudiInterface GaudiInterface-* External (no_version_directory)
#           use AthAllocators AthAllocators-* Control (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use GaudiInterface GaudiInterface-* External (no_version_directory)
#             use AtlasBoost AtlasBoost-* External (no_version_directory)
#           use AthContainersInterfaces AthContainersInterfaces-* Control (no_version_directory)
#         use SGTools SGTools-* Control (no_version_directory)
#         use CxxUtils CxxUtils-* Control (no_version_directory)
#       use SGTools SGTools-* Control (no_version_directory)
#       use IOVDbDataModel IOVDbDataModel-* Database (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use GaudiInterface GaudiInterface-* External (no_version_directory)
#         use CLIDSvc CLIDSvc-* Control (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use SGTools SGTools-* Control (no_version_directory)
#           use AtlasPython AtlasPython-* External (no_auto_imports) (no_version_directory)
#         use AthenaPoolUtilities AthenaPoolUtilities-* Database/AthenaPOOL (no_version_directory)
#           use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#           use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#             use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#             use CORAL v* LCG_Interfaces (no_version_directory) (native_version=3_1_0)
#             use AtlasReflex AtlasReflex-00-* External (no_auto_imports) (no_version_directory)
#           use AthenaKernel AthenaKernel-* Control (no_version_directory)
#           use CLIDSvc CLIDSvc-* Control (no_version_directory)
#           use DataModel DataModel-* Control (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use SGTools SGTools-* Control (no_version_directory)
#             use AthAllocators AthAllocators-* Control (no_version_directory)
#             use AthLinks AthLinks-* Control (no_version_directory)
#             use AthContainers AthContainers-* Control (no_version_directory)
#             use CxxUtils CxxUtils-* Control (no_version_directory)
#           use PersistentDataModel PersistentDataModel-* Database (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#             use GaudiInterface GaudiInterface-* External (no_version_directory)
#             use CLIDSvc CLIDSvc-* Control (no_version_directory)
#             use SGTools SGTools-* Control (no_version_directory)
#           use DBDataModel DBDataModel-* Database/AthenaPOOL (no_version_directory)
#             use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#             use CLIDSvc CLIDSvc-* Control (no_version_directory)
#             use DataModel DataModel-* Control (no_version_directory)
#         use AthenaKernel AthenaKernel-* Control (no_version_directory)
#   use AtlasAuthentication AtlasAuthentication-* Database/ConnectionManagement (no_auto_imports) (no_version_directory) (native_version=v18)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use pytools * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.9_python2.7)
#     use LCG_Configuration v*  (no_version_directory)
#     use LCG_Settings v*  (no_version_directory)
#     use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.9.p1)
#     use mysql v* LCG_Interfaces (no_version_directory) (native_version=5.5.27)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#   use pyanalysis * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.5_python2.7)
#     use LCG_Configuration v*  (no_version_directory)
#     use LCG_Settings v*  (no_version_directory)
#     use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.9.p1)
#     use blas v* LCG_Interfaces (no_version_directory) (native_version=20110419)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#     use lapack v* LCG_Interfaces (no_version_directory) (native_version=3.5.0)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#       use blas v* LCG_Interfaces (no_version_directory) (native_version=20110419)
#   use fftw * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.1.2)
#     use LCG_Configuration v*  (no_version_directory)
#     use LCG_Settings v*  (no_version_directory)
#   use xrootd * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=4.2.3)
#   use AthenaCommon AthenaCommon-* Control (no_auto_imports) (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use AthenaKernel AthenaKernel-* Control (no_auto_imports) (no_version_directory)
#   use AthenaServices AthenaServices-* Control (no_auto_imports) (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use SGTools SGTools-* Control (no_auto_imports) (no_version_directory)
#   use StoreGate StoreGate-* Control (no_auto_imports) (no_version_directory)
#   use GaudiInterface GaudiInterface-* External (no_auto_imports) (no_version_directory)
#   use PartPropSvc v*  (no_auto_imports) (no_version_directory)
#     use GaudiPolicy *  (no_version_directory)
#     use GaudiKernel *  (no_version_directory)
#     use HepPDT * LCG_Interfaces (no_version_directory) (native_version=2.06.01)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
#   use yampl yampl-* External (no_auto_imports) (no_version_directory) (native_version=1.0)
#     use ExternalPolicy ExternalPolicy-00-* External (no_version_directory)
#   use AtlasPOOL AtlasPOOL-* External (no_auto_imports) (no_version_directory)
#     use ExternalPolicy ExternalPolicy-* External (no_version_directory)
#     use mysql v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=5.5.27)
#     use POOLCore POOLCore-* Database/APR (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#       use AtlasBoost AtlasBoost-* External (no_version_directory)
#     use CollectionBase CollectionBase-* Database/APR (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#       use FileCatalog FileCatalog-* Database/APR (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#         use POOLCore POOLCore-* Database/APR (no_version_directory)
#     use CollectionUtilities CollectionUtilities-* Database/APR (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#       use PersistentDataModel PersistentDataModel-* Database (no_version_directory)
#       use CollectionBase CollectionBase-* Database/APR (no_version_directory)
#       use TrigCollQuery TrigCollQuery-* Database/APR (no_version_directory)
#         use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#         use GaudiInterface GaudiInterface-* External (no_version_directory)
#         use AthenaKernel AthenaKernel-* Control (no_version_directory)
#         use AthenaBaseComps AthenaBaseComps-* Control (no_version_directory)
#     use StorageSvc StorageSvc-* Database/APR (no_version_directory)
#       use uuid * LCG_Interfaces (no_version_directory) (native_version=dummy)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use AtlasReflex AtlasReflex-* External (no_version_directory)
#       use AtlasCORAL AtlasCORAL-* External (no_version_directory)
#       use CxxUtils CxxUtils-* Control (no_version_directory)
#       use PersistentDataModel PersistentDataModel-* Database (no_version_directory)
#       use DataModelRoot DataModelRoot-* Control (no_version_directory)
#     use PersistencySvc PersistencySvc-* Database/APR (no_version_directory)
#       use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#       use POOLCore POOLCore-* Database/APR (no_version_directory)
#       use StorageSvc StorageSvc-* Database/APR (no_version_directory)
#       use DataModelRoot DataModelRoot-* Control (no_version_directory)
#   use Asg_Test Asg_Test-* AsgExternal (no_auto_imports) (no_version_directory)
#     use AtlasPolicy AtlasPolicy-*  (no_version_directory)
# use testMetMaker *  (no_auto_imports) (no_version_directory)
#   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use GaudiInterface GaudiInterface-* External (no_version_directory)
# use TriggerList *  (no_auto_imports) (no_version_directory)
#   use AtlasPolicy AtlasPolicy-*  (no_version_directory)
#   use GaudiInterface GaudiInterface-* External (no_version_directory)
#
# Selection :
use CMT v1r25p20160527 (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25)
use CodeCheck CodeCheck-01-02-03 Tools (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use LCG_Platforms v1  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e)
use AtlasCompilers AtlasCompilers-00-00-25 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use LCG_Configuration v1  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e)
use LCG_Settings v1  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e)
use HepPDT v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use fftw v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use blas v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use lapack v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use mysql v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use uuid v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use valgrind v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use RELAX v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use CLHEP CLHEP-00-67-00-03 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/GAUDI/v26r2p1-lcg81e) (no_auto_imports)
use AIDA v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use fastjet v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use AtlasDoxygen AtlasDoxygen-00-04-10 Tools (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use AtlasCommonPolicy AtlasCommonPolicy-00-00-56  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use xrootd v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use GCCXML v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use libunwind v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use tcmalloc v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use Python v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use pyanalysis v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use pytools v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use Boost v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use CORAL v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use ROOT v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use COOL v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use Reflex v1 LCG_Interfaces (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e) (no_auto_imports)
use GaudiPolicy GaudiPolicy-15-05-00  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/GAUDI/v26r2p1-lcg81e)
use GaudiPluginService GaudiPluginService-02-02-00  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/GAUDI/v26r2p1-lcg81e) (no_auto_imports)
use GaudiKernel GaudiKernel-31-05-04  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/GAUDI/v26r2p1-lcg81e) (no_auto_imports)
use PartPropSvc PartPropSvc-06-03-01  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/GAUDI/v26r2p1-lcg81e) (no_auto_imports)
use PlatformPolicy PlatformPolicy-00-00-20 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use AtlasExternalArea AtlasExternalArea-00-00-27 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use SLC5_Compat SLC5_Compat-00-00-02 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use SLC4_Compat SLC4_Compat-00-10-01 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasFortranPolicy AtlasFortranPolicy-00-00-81  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasFastJet AtlasFastJet-00-00-30 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use Mac105_Compat Mac105_Compat-00-00-01 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use ExternalPolicy ExternalPolicy-00-01-72 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use yampl yampl-00-00-03 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use GaudiInterface GaudiInterface-01-03-04 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasRELAX AtlasRELAX-00-01-00 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasROOT AtlasROOT-02-03-28 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasReflex AtlasReflex-00-03-10 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasCORAL AtlasCORAL-00-00-10 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasCOOL AtlasCOOL-00-00-11 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasHepMC AtlasHepMC-00-00-23 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasCLHEP AtlasCLHEP-00-00-11-01 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasAIDA AtlasAIDA-00-01-02 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasPython AtlasPython-00-01-07 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasPyROOT AtlasPyROOT-00-01-01 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use CheckerGccPlugins CheckerGccPlugins-00-01-85 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use AtlasCxxPolicy AtlasCxxPolicy-00-00-77  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use AtlasPolicy AtlasPolicy-01-08-46-04  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use TriggerList TriggerList-00-00-00  (/home/paredes/TestArea/athenaMetTest2) (no_auto_imports)
use testMetMaker testMetMaker-00-00-00  (/home/paredes/TestArea/athenaMetTest2) (no_auto_imports)
use Asg_Test Asg_Test-02-04-03 AsgExternal (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AthenaServices AthenaServices-01-59-25-03 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AthenaCommon AthenaCommon-03-03-13 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasAuthentication AtlasAuthentication-00-05-06 Database/ConnectionManagement (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use xAODRootAccessInterfaces xAODRootAccessInterfaces-00-00-07 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use Scripts Scripts-00-01-88 Tools (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use DataModelRoot DataModelRoot-00-00-20 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use Lhapdf Lhapdf-06-01-05-06 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasValgrind AtlasValgrind-00-01-17 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasFastJetContrib AtlasFastJetContrib-01-22-03 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use PyCmt PyCmt-00-00-47 Tools (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasTBB AtlasTBB-00-00-09 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasEigen AtlasEigen-00-00-09 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasBoost AtlasBoost-00-00-11 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use POOLCore POOLCore-00-04-03 Database/APR (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use FileCatalog FileCatalog-00-01-08 Database/APR (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use CollectionBase CollectionBase-00-02-09 Database/APR (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AthAllocators AthAllocators-00-01-12 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use CxxUtils CxxUtils-00-01-57 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AthenaKernel AthenaKernel-00-57-00-01 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use SGTools SGTools-00-26-03-01 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use CLIDSvc CLIDSvc-00-05-02 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use PersistentDataModel PersistentDataModel-00-00-47 Database (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use StorageSvc StorageSvc-00-05-11 Database/APR (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use PersistencySvc PersistencySvc-00-02-05 Database/APR (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AthLinks AthLinks-00-02-25 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AthContainersInterfaces AthContainersInterfaces-00-01-33 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use StoreGate StoreGate-03-05-01-02 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AthenaBaseComps AthenaBaseComps-00-07-02-01 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use TrigCollQuery TrigCollQuery-01-00-04 Database/APR (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use CollectionUtilities CollectionUtilities-00-02-24 Database/APR (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AtlasPOOL AtlasPOOL-00-02-01 External (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AthContainers AthContainers-00-02-61 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use DataModel DataModel-00-23-71 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use DBDataModel DBDataModel-00-08-02 Database/AthenaPOOL (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AthenaPoolUtilities AthenaPoolUtilities-00-07-19 Database/AthenaPOOL (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use IOVDbDataModel IOVDbDataModel-00-00-28 Database (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use xAODCore xAODCore-00-01-23 Event/xAOD (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use xAODEventFormat xAODEventFormat-00-00-15 Event/xAOD (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use xAODRootAccess xAODRootAccess-00-01-59 Control (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AsgTools AsgTools-00-01-06 Control/AthToolSupport (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use PathResolver PathResolver-00-02-33 Tools (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25) (no_auto_imports)
use AthAnalysisBaseRunTime AthAnalysisBaseRunTime-00-00-12  (/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25)
use CMTUSERCONTEXT v0 (/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt)
----------> tags
x86_64-slc6-gcc49-opt (from CMTCONFIG) package [LCG_Platforms PlatformPolicy] implies [target-x86_64 target-slc6 target-gcc49 target-opt Linux slc6 64 gcc-4.9 opt x86_64-slc6-gcc49]
ATLAS (from arguments) package [GaudiPolicy] implies [use-shared-dir no-pyzip] applied [ExternalPolicy]
ManaCore (from arguments)
AthAnalysisBase (from arguments)
CMTv1 (from CMTVERSION)
CMTr25 (from CMTVERSION)
CMTp20160527 (from CMTVERSION)
Linux (from uname) package [CMT LCG_Platforms AtlasCxxPolicy AtlasPolicy] implies [Unix host-linux cpp_native_dependencies]
STANDALONE (from CMTSITE)
CMTUSERCONTEXT_no_config (from PROJECT) excludes [CMTUSERCONTEXT_config]
CMTUSERCONTEXT_no_root (from PROJECT) excludes [CMTUSERCONTEXT_root]
CMTUSERCONTEXT_cleanup (from PROJECT) excludes [CMTUSERCONTEXT_no_cleanup]
CMTUSERCONTEXT_scripts (from PROJECT) excludes [CMTUSERCONTEXT_no_scripts]
CMTUSERCONTEXT_no_prototypes (from PROJECT) excludes [CMTUSERCONTEXT_prototypes]
CMTUSERCONTEXT_with_installarea (from PROJECT) excludes [CMTUSERCONTEXT_without_installarea]
CMTUSERCONTEXT_without_version_directory (from PROJECT) excludes [CMTUSERCONTEXT_with_version_directory]
TestArea_no_config (from PROJECT) excludes [TestArea_config]
TestArea_no_root (from PROJECT) excludes [TestArea_root]
TestArea_cleanup (from PROJECT) excludes [TestArea_no_cleanup]
TestArea_scripts (from PROJECT) excludes [TestArea_no_scripts]
TestArea_no_prototypes (from PROJECT) excludes [TestArea_prototypes]
TestArea_with_installarea (from PROJECT) excludes [TestArea_without_installarea]
TestArea_without_version_directory (from PROJECT) excludes [TestArea_with_version_directory]
TestArea (from PROJECT)
AthAnalysisBase_no_config (from PROJECT) excludes [AthAnalysisBase_config]
AthAnalysisBase_no_root (from PROJECT) excludes [AthAnalysisBase_root]
AthAnalysisBase_cleanup (from PROJECT) excludes [AthAnalysisBase_no_cleanup]
AthAnalysisBase_scripts (from PROJECT) excludes [AthAnalysisBase_no_scripts]
AthAnalysisBase_no_prototypes (from PROJECT) excludes [AthAnalysisBase_prototypes]
AthAnalysisBase_with_installarea (from PROJECT) excludes [AthAnalysisBase_without_installarea]
AthAnalysisBase_without_version_directory (from PROJECT) excludes [AthAnalysisBase_with_version_directory]
GAUDI_no_config (from PROJECT) excludes [GAUDI_config]
GAUDI_root (from PROJECT) excludes [GAUDI_no_root]
GAUDI_cleanup (from PROJECT) excludes [GAUDI_no_cleanup]
GAUDI_scripts (from PROJECT) excludes [GAUDI_no_scripts]
GAUDI_prototypes (from PROJECT) excludes [GAUDI_no_prototypes]
GAUDI_with_installarea (from PROJECT) excludes [GAUDI_without_installarea]
GAUDI_without_version_directory (from PROJECT) excludes [GAUDI_with_version_directory]
LCGCMT_no_config (from PROJECT) excludes [LCGCMT_config]
LCGCMT_no_root (from PROJECT) excludes [LCGCMT_root]
LCGCMT_cleanup (from PROJECT) excludes [LCGCMT_no_cleanup]
LCGCMT_scripts (from PROJECT) excludes [LCGCMT_no_scripts]
LCGCMT_prototypes (from PROJECT) excludes [LCGCMT_no_prototypes]
LCGCMT_with_installarea (from PROJECT) excludes [LCGCMT_without_installarea]
LCGCMT_without_version_directory (from PROJECT) excludes [LCGCMT_with_version_directory]
x86_64 (from package CMT) package [LCG_Platforms] implies [host-x86_64] applied [CMT]
sl69 (from package CMT) package [PlatformPolicy] implies [host-slc6] applied [CMT]
gcc493 (from package CMT) applied [CMT]
Unix (from package CMT) package [LCG_Platforms] implies [host-unix] excludes [WIN32 Win32]
c_native_dependencies (from package CMT) activated GaudiPolicy
cpp_native_dependencies (from package CMT) activated GaudiPolicy
/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25:/cvmfs/atlas.cern.ch/repo/sw/tdaq/tdaqnotProject (from package ExternalPolicy) applied [ExternalPolicy]
target-unix (from package LCG_Settings) activated LCG_Platforms
target-x86_64 (from package LCG_Settings) activated LCG_Platforms
target-gcc49 (from package LCG_Settings) package [LCG_Platforms] implies [target-gcc4 target-lcg-compiler lcg-compiler target-c11] activated LCG_Platforms
host-x86_64 (from package LCG_Settings) activated LCG_Platforms
target-slc (from package LCG_Settings) package [LCG_Platforms] implies [target-linux] activated LCG_Platforms
target-gcc (from package LCG_Settings) activated LCG_Platforms
target-gcc4 (from package LCG_Settings) package [LCG_Platforms] implies [target-gcc] activated LCG_Platforms
target-lcg-compiler (from package LCG_Settings) activated LCG_Platforms
host-linux (from package LCG_Platforms) package [LCG_Platforms] implies [host-unix]
host-unix (from package LCG_Platforms)
host-slc6 (from package LCG_Platforms) package [LCG_Platforms] implies [host-slc] activated PlatformPolicy
host-slc (from package LCG_Platforms) package [LCG_Platforms] implies [host-linux] activated PlatformPolicy
target-opt (from package LCG_Platforms)
target-slc6 (from package LCG_Platforms) package [LCG_Platforms] implies [target-slc]
target-linux (from package LCG_Platforms) package [LCG_Platforms] implies [target-unix]
lcg-compiler (from package LCG_Platforms)
target-c11 (from package LCG_Platforms)
ROOT_GE_5_15 (from package LCG_Configuration) applied [LCG_Configuration]
ROOT_GE_5_19 (from package LCG_Configuration) applied [LCG_Configuration]
ROOT_GE_6_00 (from package LCG_Configuration) applied [LCG_Configuration]
use-shared-dir (from package GaudiPolicy)
do_genconf (from package GaudiPolicy) applied [AtlasPolicy] activated AtlasPolicy
no-pyzip (from package GaudiPolicy)
separate-debug (from package AtlasCommonPolicy) excludes [no-separate-debug] applied [AtlasCommonPolicy]
NICOS (from package AtlasCommonPolicy) package AtlasCommonPolicy excludes [NICOSrel_nightly] applied [AtlasCommonPolicy]
LCGCMT_INSTALLED (from package PlatformPolicy) applied [PlatformPolicy ExternalPolicy]
block-tdaqc (from package PlatformPolicy) applied [PlatformPolicy ExternalPolicy]
opt (from package PlatformPolicy) package [AtlasPolicy] implies [optimized]
gcc (from package PlatformPolicy)
64 (from package PlatformPolicy) package [PlatformPolicy] implies [target-64]
gcc-4.9 (from package PlatformPolicy) package [PlatformPolicy] implies [gcc49x gcc49 gcc]
gcc49x (from package PlatformPolicy)
gcc49 (from package PlatformPolicy)
slc6 (from package PlatformPolicy)
x86_64-slc6-gcc49 (from package PlatformPolicy)
target-64 (from package PlatformPolicy)
asNeeded (from package PlatformPolicy) applied [PlatformPolicy]
CheckerGccPlugins_project_AthAnalysisBase (from package CheckerGccPlugins) applied [CheckerGccPlugins]
optimized (from package AtlasPolicy) package [AtlasPolicy] implies [opt]
HasAthenaRunTime (from package AtlasPolicy) applied [AtlasPolicy]
SITE_ (from package AtlasPolicy) applied [AtlasPolicy]
HAS_FORTRAN_RUNTIME (from package AtlasFortranPolicy)
HAS_FORTRAN (from package AtlasFortranPolicy)
HAS_GFO (from package AtlasFortranPolicy) package [AtlasFortranPolicy] implies [HAS_FORTRAN HAS_GFO_RUNTIME] applied [AtlasFortranPolicy]
HAS_GFO_RUNTIME (from package AtlasFortranPolicy) package [AtlasFortranPolicy] implies [HAS_FORTRAN_RUNTIME]
ROOTBasicLibs (from package AtlasROOT) applied [AtlasROOT]
ROOTCintexLibs (from package AtlasROOT) applied [xAODCore] activated xAODCore
ROOTNetLibs (from package AtlasROOT) applied [xAODRootAccess] activated xAODRootAccess
NEEDS_CORAL_RELATIONAL_ACCESS (from package CORAL) applied [AtlasCORAL] activated AtlasCORAL
NEEDS_CORAL_BASE (from package CORAL) applied [AthenaPoolUtilities] activated AthenaPoolUtilities
NEEDS_PYCOOL (from package COOL) applied [AtlasCOOL] activated AtlasCOOL
HAVE_GAUDI_PLUGINSVC (from package GaudiPluginService) applied [GaudiPluginService]
NotAtlasP1 (from package PathResolver) applied [PathResolver]
ASGSeries24 (from package Asg_Test) applied [Asg_Test]
no_pack_dist_check (from package WorkArea) applied [WorkArea]
----------> CMTPATH
# Add path /cvmfs/atlas.cern.ch/repo/tools/slc6/cmt from CMTUSERCONTEXT
# Add path /home/paredes/TestArea/athenaMetTest2 from initialization
# Add path /cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/AthAnalysisBase/2.4.25 from initialization
# Add path /cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/GAUDI/v26r2p1-lcg81e from ProjectPath
# Add path /cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.25/LCGCMT/LCGCMT_81e from ProjectPath
